apiVersion: apps/v1
kind: Deployment
metadata:
  name: diabetes-model-deployment
  labels:
    app: diabetes-model
spec:
  replicas: 2
  selector:
    matchLabels:
      app: diabetes-model
  template:
    metadata:
      labels:
        app: diabetes-model
    spec:
      containers:
      - name: diabetes-model-container
        image: tolulopeodetola1/diabetes-model-demo:latest
        ports:
        - containerPort: 8000
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: diabetes-model-service
spec:
  selector:
    app: diabetes-model
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: LoadBalancer